FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY roborock-mqtt-loxone /roborock-mqtt-loxone
COPY web/dist /web/dist

USER nonroot:nonroot

ENTRYPOINT ["/roborock-mqtt-loxone", "/var/lib/roborock-mqtt-loxone/config.json"]
