services:
  roborock-mqtt-loxone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roborock-mqtt-loxone
    restart: unless-stopped
    volumes:
      - ../production/config:/var/lib/roborock-mqtt-loxone
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
